export const FETCH_PLACED_ORDER_START = 'FETCH_PLACED_ORDER_START';
export const FETCH_PLACED_ORDER_SUCCESS = 'FETCH_PLACED_ORDER_SUCCESS';
export const FETCH_PLACED_ORDER_FAILURE = 'FETCH_PLACED_ORDER_FAILURE';

export const CLEAR_PLACED_ORDER = 'CLEAR_PLACED_ORDER';