export const FETCH_POINTS_START = 'FETCH_POINTS_START';
export const FETCH_POINTS_SUCCESS = 'FETCH_POINTS_SUCCESS';
export const FETCH_POINTS_FAILURE = 'FETCH_POINTS_FAILURE';

export const FETCH_MARKERS = 'FETCH_MARKERS';