export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';
export const COMPLETE_MAP_STAGE = 'COMPLETE_MAP_STAGE';
export const SET_CURRENT_CAR = 'SET_CURRENT_CAR';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const COMPLETE_CAR_STAGE = 'COMPLETE_CAR_STAGE';
export const COMPLETE_ADDITIONAL_STAGE = 'COMPLETE_ADDITIONAL_STAGE';
export const UNCOMPLETE_ADDITIONAL_STAGE = 'UNCOMPLETE_ADDITIONAL_STAGE';
export const SET_CURRENT_PRICE = 'SET_CURRENT_PRICE';

export const FETCH_ORDER_STATUS_ID_START = 'FETCH_ORDER_STATUS_ID_START';
export const FETCH_ORDER_STATUS_ID_SUCCESS = 'FETCH_ORDER_STATUS_ID_SUCCESS';
export const FETCH_ORDER_STATUS_ID_FAILURE = 'FETCH_ORDER_STATUS_ID_FAILURE';