export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';
export const COMPLETE_MAP_STAGE = 'COMPLETE_MAP_STAGE';
export const SET_CURRENT_CAR = 'SET_CURRENT_CAR';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const COMPLETE_CAR_STAGE = 'COMPLETE_CAR_STAGE';
export const COMPLETE_ADDITIONAL_STAGE = 'COMPLETE_ADDITIONAL_STAGE';